name: Fetch MSN News Links

on:
  schedule:
    - cron: '25 4 * * *'   # UTC 04:00 → 北京时间 12:00
    - cron: '25 16 * * *'  # UTC 16:00 → 北京时间 00:00

  workflow_dispatch:  # 允许手动触发

  

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 赋予写入权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios fs path nodemailer

      - name: Fetch MSN news links
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: node .github/scripts/fetch_msn_news.js

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add links.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update links.json"
            # 使用普通的 git pull 并自动合并更改
            git pull origin main --no-edit
            git push origin main
          fi
